Repository hd-team4/dorakdorak-frontend, pull requests merged in 2025-06, with the labels that each got.

#11 [#10] 도시락 조회 리스트 페이지 구현
  src/api/DosirakList.ts
  src/components/common/SortOptions.tsx
  src/components/common/category/CategoryList.tsx
  src/components/list/DosirakCard.tsx
  src/components/list/DosirakList.tsx
  src/constants/categories.ts
  src/constants/sortOptions.ts
  src/css/common/SortOptions.css
  src/css/list/DosirakCard.css
  src/css/list/DosirakList.css
  src/css/list/Menu.css
  src/css/main/DosirakCard.css
  src/mock/DosirakListMockData.ts
  src/pages/Main.tsx
  src/pages/Menu.tsx
  src/types/DosirakList.ts
  src/utils/storageType.ts
Labels: ✨ Feature

#14 [#13] CSS 네임 수정
  src/components/common/Header.tsx
  src/components/common/SortOptions.tsx
  src/components/common/category/CategoryButton.tsx
  src/components/list/DosirakCard.tsx
  src/components/main/SectionTitle.tsx
  src/css/common/Category.css
  src/css/common/Header.css
  src/css/common/SortOptions.css
  src/css/list/DosirakCard.css
  src/css/list/Menu.css
  src/css/main/SectionTitle.css
  src/pages/Menu.tsx
Labels: 🛠️ Refactor

#15 Feat/9
  package-lock.json
  package.json
  src/mock/AllergyMockData.ts
  src/mock/universityMockData.ts
  src/pages/SignUp.tsx
Labels: ✨ Feature

#21 [#20] 커스텀 도시락 랭킹 페이지 구현
  src/App.css
  src/assets/images/icon/check-green.png
  src/assets/images/icon/check-white.png
  src/components/customRanking/CustomDosirakCard.tsx
  src/components/customRanking/CustomDosirakList.tsx
  src/components/customRanking/VoteModal.tsx
  src/css/common/SectionHeader.module.css
  src/css/common/SortOptions.module.css
  src/css/customRanking/CustomDosirak.module.css
  src/css/customRanking/VoteModal.module.css
  src/mock/CustomDosirakRankingMockData.ts
  src/pages/CustomRanking.tsx
  src/types/DosirakList.ts
Labels: ✨ Feature

#26 [#25] 대학교 제로웨이스트 랭킹 페이지 구현
  src/api/UniversityRanking.ts
  src/assets/images/icon/medal_bronze.png
  src/assets/images/icon/medal_gold.png
  src/assets/images/icon/medal_silver.png
  src/assets/images/intro/zero-waste.png
  src/assets/images/mock/university.png
  src/components/common/IntroSection.tsx
  src/components/zeroWaste/UniversityRanking.tsx
  src/constants/medalMap.ts
  src/css/common/IntroSection.module.css
  src/css/zeroWaste/RankingList.module.css
  src/mock/UniversityRankingMockData.ts
  src/pages/ZeroWasteRanking.tsx
  src/types/UniversityRanking.ts
Labels: ✨ Feature

#28 [#16] 로그인 기능 구현
  package-lock.json
  package.json
  src/App.tsx
  src/api/authApi.ts
  src/api/axiosInstance.ts
  src/components/common/Header.tsx
  src/components/login/EmailInput.tsx
  src/components/login/ErrorMessage.tsx
  src/components/login/PasswordInput.tsx
  src/components/login/SignupLink.tsx
  src/components/login/SubmitButton.tsx
  src/css/login/login.module.css
  src/hooks/useLoginForm.ts
  src/pages/Login.tsx
  src/store/authStore.ts
  tsconfig.json
Labels: ✨ Feature

#29 [#27] 커스텀 도시락 생성 겸 상세 페이지 구현
  src/App.css
  src/App.tsx
  src/api/CustomDosirakGenerate.ts
  src/assets/images/icon/caution.png
  src/components/common/Spinner.tsx
  src/components/common/select/QuestionGrid.tsx
  src/components/customRanking/CustomDosirakCard.tsx
  src/css/common/Footer.module.css
  src/css/common/Spinner.module.css
  src/css/customGenerate/CustomDetail.module.css
  src/css/customRanking/CustomDosirak.module.css
  src/css/detail/NutritionTable.module.css
  src/mock/CustomDosirakDetailMockData.ts
  src/pages/CustomDetail.tsx
  src/pages/CustomDosirak.tsx
  src/pages/Detail.tsx
  src/types/CustomDosirakGenerate.ts
Labels: ✨ Feature

#32 [#30] 공동주문 페이지 구현
  package-lock.json
  package.json
  src/components/common/Header.tsx
  src/components/common/select/SelectBox.tsx
  src/components/order/Calendar.tsx
  src/components/order/DosirakOrderSection.tsx
  src/constants/times.ts
  src/css/common/Header.module.css
  src/css/common/SelectableItem.module.css
  src/css/order/CalendarComponent.module.css
  src/css/order/GroupOrder.module.css
  src/pages/GroupOrder.tsx
  src/utils/price.ts
Labels: ✨ Feature

#31 [#12] 마이페이지 구현
  src/App.tsx
  src/api/Mypage.ts
  src/components/mypage/CustomDosirakList.tsx
  src/components/mypage/OrderHistoryList.tsx
  src/components/mypage/OrderSummaryStatus.tsx
  src/components/mypage/ZeroWastePromo.tsx
  src/constants/orderStatus.ts
  src/css/main/MyCustomDosiraks.module.css
  src/css/main/MyGroupOrders.module.css
  src/css/main/MyNormalOrders.module.css
  src/css/main/Mypage.module.css
  src/css/mypage/CustomDosirakList.module.css
  src/css/mypage/OrderHistoryList.module.css
  src/css/mypage/OrderSummaryStatus.module.css
  src/css/mypage/ZeroWastePromo.module.css
  src/mock/MypageMockData.ts
  src/pages/MyCustomDosiraks.tsx
  src/pages/MyGroupOrders.tsx
  src/pages/MyNormalOrders.tsx
  src/pages/Mypage.tsx
  src/types/Mypage.ts
Labels: ✨ Feature

#39 [#38] 어드민 통계 페이지 구현
  package-lock.json
  package.json
  src/components/adminManagement/CustomTooltip.tsx
  src/components/common/DosirakSearchInput.tsx
  src/css/common/DosirakSearchInput.module.css
  src/mock/AdminPopularDosiraks.ts
  src/pages/admin/OrderStatistics.tsx
  src/pages/admin/PopularityStatistics.tsx
  src/pages/admin/SalesStatistics.tsx
  src/types/AdminManagement.ts
  src/types/AdminStatistics.ts
Labels: ✨ Feature

#48 [#47] 일반 도시락 리스트 조회, 상세 페이지 조회 API 연결
  src/api/DosirakDetail.ts
  src/api/DosirakList.ts
  src/css/common/Category.module.css
  src/css/list/DosirakCard.module.css
  src/css/list/DosirakList.module.css
  src/pages/Detail.tsx
  src/pages/Menu.tsx
  src/types/DosirakList.ts
Labels: ✨ Feature

#51 [#49] API 연결
  src/api/CustomDosirakGenerate.ts
  src/api/GroupOrder.ts
  src/api/UniversityRanking.ts
  src/api/axiosInstance.ts
  src/components/common/QuantitySelector.tsx
  src/components/common/select/QuestionGrid.tsx
  src/components/customRanking/CustomDosirakCard.tsx
  src/components/customRanking/CustomDosirakList.tsx
  src/components/detail/DosirakInfo.tsx
  src/components/order/DosirakOrderSection.tsx
  src/constants/foodOptions.ts
  src/constants/times.ts
  src/css/common/SelectableItem.module.css
  src/pages/CustomDetail.tsx
  src/pages/CustomDosirak.tsx
  src/pages/CustomRanking.tsx
  src/pages/Detail.tsx
  src/pages/GroupOrder.tsx
  src/pages/ZeroWasteRanking.tsx
  src/types/CustomDosirakGenerate.ts
  src/types/DosirakList.ts
  src/types/GroupOrder.ts
  src/utils/categoryTransfer.ts
Labels: ✨ Feature

#50 [#46] 마이페이지 API 연결 및 무한 스크롤 적용
  src/App.tsx
  src/api/Mypage.ts
  src/components/mypage/CustomDosirakList.tsx
  src/components/mypage/OrderHistoryList.tsx
  src/constants/orderStatus.ts
  src/css/mypage/OrderHistoryList.module.css
  src/pages/MyCustomDosiraks.tsx
  src/pages/MyGroupOrders.tsx
  src/pages/MyNormalOrders.tsx
  src/pages/Mypage.tsx
  src/types/Mypage.ts
Labels: ✨ Feature

#52 [#45] 결제 API 및 토스페이먼츠 연동
  package-lock.json
  package.json
  src/App.tsx
  src/api/Payment.ts
  src/components/detail/DosirakInfo.tsx
  src/components/order/DosirakOrderSection.tsx
  src/components/order/OrderSuccessTable.tsx
  src/css/order/OrderFail.module.css
  src/pages/GroupOrder.tsx
  src/pages/OrderFail.tsx
  src/pages/OrderSuccess.tsx
  src/pages/OrderSuccessPage.tsx
  src/types/OrderSuccess.ts
  src/types/Payment.ts
Labels: ✨ Feature

#62 [#61] 제로웨이스트 프로모션 컴포넌트 UI 수정
  src/components/mypage/ZeroWastePromo.tsx
  src/css/mypage/ZeroWastePromo.module.css
Labels: 🛠️ Refactor

#60 [#57] 어드민 페이지 API 연결
  src/api/AdminApi.ts
  src/components/adminManagement/AdminCustomDosirakList.tsx
  src/components/detail/DosirakInfo.tsx
  src/components/order/DosirakOrderSection.tsx
  src/pages/admin/DosirakManagement.tsx
  src/pages/admin/OrderManagement.tsx
  src/pages/admin/OrderStatistics.tsx
  src/pages/admin/PopularityStatistics.tsx
  src/pages/admin/SalesStatistics.tsx
Labels: ✨ Feature

#64 [#63] 메인 페이지 API 연결 및 디자인 수정
  src/assets/images/mock/custom1.png
  src/assets/images/mock/custom2.png
  src/assets/images/mock/custom3.png
  src/components/main/DosirakSection.tsx
  src/components/main/RankingList.tsx
  src/css/list/Menu.module.css
  src/css/login/login.module.css
  src/css/main/Carousel.module.css
  src/css/signup/Signup.module.css
  src/pages/CustomRanking.tsx
  src/pages/GroupOrder.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/Menu.tsx
  src/types/AdminStatistics.ts
Labels: ✨ Feature

#67 디자인 수정
  src/css/main/MyCustomDosiraks.module.css
  src/css/main/MyGroupOrders.module.css
  src/css/main/MyNormalOrders.module.css
  src/css/main/Mypage.module.css
  src/css/mypage/CustomDosirakList.module.css
  src/css/mypage/OrderHistoryList.module.css
  src/css/mypage/OrderSummaryStatus.module.css
  src/pages/Mypage.tsx
Labels: 🌏 Deploy

#68 디자인 수정
  src/assets/images/mock/banner1.png
  src/assets/images/mock/banner2.png
  src/components/main/Carousel.tsx
  src/css/main/Carousel.module.css
Labels: 🌏 Deploy

#69 [DESIGN] 결제 완료 페이지 CSS 수정
  src/css/order/OrderSuccessTable.module.css
  src/pages/OrderSuccess.tsx
Labels: 🌏 Deploy

#70 커스텀 도시락 투표 버튼 CSS 수정
  src/components/customRanking/CustomDosirakCard.tsx
Labels: 🌏 Deploy

#71 주문 취소시 모달 처리
  src/pages/MyGroupOrders.tsx
  src/pages/MyNormalOrders.tsx
Labels: 🌏 Deploy

#72 [CHORE] 공동 주문 초기 날짜 설정
  src/components/order/Calendar.tsx
  src/pages/GroupOrder.tsx
Labels: 🌏 Deploy

#73 [FEAT] 할인 퍼센트에 따른 가격 수정
  src/components/detail/DosirakInfo.tsx
  src/components/list/DosirakCard.tsx
  src/components/order/Calendar.tsx
  src/components/order/DosirakOrderSection.tsx
  src/pages/Menu.tsx
Labels: 🌏 Deploy
